name: new_life
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.6
  flutter_svg: ^1.0.0
  image_picker: ^0.8.4+6
  file_picker:
  provider: ^6.0.2
  uuid: ^3.0.5
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_app_name:
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_app_name:
  name: "New Life"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - assets/
     - assets/icons/
  fonts:
    - family: Nutino
      fonts:
        - asset: fonts/Nunito-Italic-VariableFont_wght.ttf
        - asset: fonts/Nunito-VariableFont_wght.ttf

